# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: #191919;\n"
"    font-family: Rubik;\n"
"    font-size: 12pt;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.left_frame = QtWidgets.QFrame(self.centralwidget)
        self.left_frame.setGeometry(QtCore.QRect(-150, 0, 150, 500))
        self.left_frame.setStyleSheet("QFrame {\n"
"    background-color: #202020;\n"
"}")
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.lbl_file = QtWidgets.QLabel(self.left_frame)
        self.lbl_file.setGeometry(QtCore.QRect(20, 20, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_file.setFont(font)
        self.lbl_file.setStyleSheet("QLabel {\n"
"    color:  #FFFFFF;\n"
"    font-weight: 600;\n"
"}")
        self.lbl_file.setObjectName("lbl_file")
        self.btn_open = QtWidgets.QPushButton(self.left_frame)
        self.btn_open.setGeometry(QtCore.QRect(20, 46, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(-1)
        self.btn_open.setFont(font)
        self.btn_open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_open.setStyleSheet("QPushButton {\n"
"    background-color: #202020;\n"
"    text-align: left;\n"
"    color:  #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C2C2C;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_open.setIcon(icon1)
        self.btn_open.setIconSize(QtCore.QSize(18, 18))
        self.btn_open.setObjectName("btn_open")
        self.btn_saveas = QtWidgets.QPushButton(self.left_frame)
        self.btn_saveas.setGeometry(QtCore.QRect(20, 75, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(-1)
        self.btn_saveas.setFont(font)
        self.btn_saveas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_saveas.setStyleSheet("QPushButton {\n"
"    background-color: #202020;\n"
"    text-align: left;\n"
"    color:  #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C2C2C;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/save as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_saveas.setIcon(icon2)
        self.btn_saveas.setIconSize(QtCore.QSize(18, 18))
        self.btn_saveas.setObjectName("btn_saveas")
        self.btn_back = QtWidgets.QPushButton(self.left_frame)
        self.btn_back.setGeometry(QtCore.QRect(116, 10, 24, 24))
        self.btn_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back.setStyleSheet("QPushButton {\n"
"    background-color: #202020;\n"
"    border:  none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2C2C2C;\n"
"}")
        self.btn_back.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon3)
        self.btn_back.setIconSize(QtCore.QSize(24, 24))
        self.btn_back.setObjectName("btn_back")
        self.btn_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_menu.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.btn_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_menu.setStyleSheet("QPushButton {\n"
"    background-color: #191919;\n"
"    border:  none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #202020;\n"
"}")
        self.btn_menu.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon4)
        self.btn_menu.setIconSize(QtCore.QSize(36, 36))
        self.btn_menu.setObjectName("btn_menu")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(60, 10, 640, 380))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    background-color: #191919;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #FFFFFF;\n"
"    width: 15px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #2C2C2C;\n"
"    border-radius: 7px;\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 640, 380))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 640, 380))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background-color: #202020;\n"
"    border: none;\n"
"    color:  #FFFFFF;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}")
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit.setObjectName("textEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btn_menu.raise_()
        self.scrollArea.raise_()
        self.left_frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SimNote"))
        self.lbl_file.setText(_translate("MainWindow", "File"))
        self.btn_open.setText(_translate("MainWindow", "Open"))
        self.btn_saveas.setText(_translate("MainWindow", "Save as"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
